namespace Nuklear.NET;

public enum NkStyleColors
{
    Text,
    Window,
    Header,
    Border,
    Button,
    ButtonHover,
    ButtonActive,
    Toggle,
    ToggleHover,
    ToggleCursor,
    Select,
    SelectActive,
    Slider,
    SliderCursor,
    SliderCursorHover,
    SliderCursorActive,
    Property,
    Edit,
    EditCursor,
    Combo,
    Chart,
    ChartColor,
    ChartColorHighlight,
    Scrollbar,
    ScrollbarCursor,
    ScrollbarCursorHover,
    ScrollbarCursorActive,
    TabHeader,
    Count,
}
